### ISSUE TITLE
Reproduce Inception Scores in the paper

### ISSUE THREAD

**Issue by tund** [hvy/chainer-GAN-denoising-feature-matching#1]
Hi @hvy ,

May I ask whether you have tried to reproduce the results (Inception scores on CIFAR10, STL10 and ImageNet datasets)? I have implemented a version in tensorflow, but could not reproduce the results. Maybe it is because my network architecture is not correct.

Thanks,

Tu

**Comment by hvy** [comment]
Hi @tund and thanks for reaching out,

I have unfortunately not measured the Inception scores with this implementation and only trained with CIFAR-10. 

Although assuming that you've seen this source code, I used a very simple architecture.
https://github.com/hvy/chainer-gan-denoising-feature-matching/blob/master/lib/models.py

**Comment by tund** [comment]
Thanks for your reply, @hvy !
Yes, I have seen your code and architecture. Actually, I have asked the author and he replied as follows:

> Our best CIFAR10 architecture was 32 feature maps in the first set of discriminator layers, then 64, then 128, at 4x4 resolution this results in a flattened representation size of 2048. The generator was double the number of parameters, so 128 z dimension -> 64 feature maps -> 32 feature maps -> 16 feature maps -> 3 RGB.

Looks like your model is much larger, especially the denoising autoencoder is really really deep.
I tested the author's model, but still could not obtain a good Inception score.

Do you have any suggestions here?

**Comment by hvy** [comment]
Hi @tund,

What results are you getting at the moment?

Regarding the denoising autoencoder, I also asked the author and he kindly told me that they were using a 10-20 layer deep fully connected neural network. This means that this 10 layered model is relatively shallow.

According to your reply from the author, it seems like the generator in the original implementation indeed uses fewer parameters. Have you tried giving it more capacity? The discriminator sounds rather similar.

Best regards.

**Comment by tund** [comment]
Hi @hvy ,
The best Inception Score I got is about 6.6 only, compared with 7.72 in the authors' paper. 
The author did not told me, and I have not found any information about the number layers of the denoising network, thus I used a very shallow one with 2 hidden layers.
I will try 10 and will let you know once I have some results.

Thanks,

Tu

**Comment by tund** [comment]
Hi @hvy ,

I use 10 hidden layers for the denoising autoencoder and got the score increasing a bit from 6.6 to 6.9, but still a way smaller than 7.72.
In the paper, the authors said that they anneal \sigma (the Gaussian corruption noise) towards 0. Do you know what the exact annealing schedule is?

Thanks,

Tu

**Comment by hvy** [comment]
Hi @tund ,

Unfortunately not. 

I can forward you the mail the I got from the author.

Best regards.
